AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: false
Lint/EmptyClass: # (new in 1.3)
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Naming/VariableNumber:
  Enabled: false
Layout/LineLength:
  Enabled: true
  Max: 150
Layout/EndOfLine:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false   
